#!/bin/bash

input="$1"

num=${input%%d*}
sides=${input##*d}

if [ -z $num ]; then
    num=1
fi
    
sum=0
for ((i=0;i<$num;i++))
    {
        value=$(shuf -i 1-$sides -n 1)
        echo "$value"
        sum=$(($sum + $value))
    }
echo "==="
echo "Sum = $sum"

